spring:
  application:
    name: SpringDockerTest
  datasource:
    url: jdbc:postgresql://192.168.0.101:5432/demo_db
    username: user
    password: user

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081