spring:
  application:
    name: SpringDockerTest
  datasource:
    url: jdbc:postgresql://192.168.0.101:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

