version: '3.1'

volumes:
  pg_demo:


services:
  demo_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=demo_db
    volumes:
      - pg_demo:/var/lib/postgresql/data
    ports:
      - "5432:5432"